In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("df_color_exp_unal0.csv") 
df1 = pd.read_csv("df_color_exp_unal1.csv") 
df2 = pd.read_csv("df_color_exp_unal2.csv") 
df3 = pd.read_csv("df_color_exp_honors0.csv")

df['group'] = 0
df1['group'] = 1
df2['group'] = 2
df3['group'] = 3

temp = df1.append(df)
temp2 = df2.append(temp)
final = df3.append(temp2)
final['ssim_exp_latest'] = final['ssim_exp'].div(100).round(6)
final.loc[final['ssim_exp_latest'] == 0.0, 'ssim_exp_latest'] = 0.01
final.loc[final['ssim_exp_latest'] == 1.0, 'ssim_exp_latest'] = 0.99
final = final.rename(columns={'comparison_type': 'type', 'stage': 'phase', 'ssim_exp_latest': 'dist_search'})
final.to_csv("final_visual.csv")

In [32]:
import pandas as pd
import numpy as np

df = pd.read_csv("df_color_exp_unal0.csv") 
df1 = pd.read_csv("df_color_exp_unal1.csv") 
df2 = pd.read_csv("df_color_exp_unal2.csv") 

df['group'] = 0
df1['group'] = 1
df2['group'] = 2

temp = df1.append(df)
final = df2.append(temp)
final['ssim_exp_new'] = final['ssim_exp'].div(100).round(6)

#final[final['ssim_exp_new'] == 1.0, 'ssim_exp_new'] = 0.99
#final[final['ssim_exp_new'] == 0.0, 'ssim_exp_new'] = 0.01
final.to_csv('final_visual.csv')

# create a list of our conditions
conditions = [
    (final['ssim_exp_new'] == 1),
    (final['ssim_exp_new'] == 0)
    ]

# create a list of the values we want to assign for each condition
values = [0.99, 0.01]

# create a new column and use np.select to assign values to it using our lists as arguments
final['tier'] = np.select(conditions, values)
final.to

AttributeError: 'DataFrame' object has no attribute 'to'

In [2]:
temp = df.append(df1, ignore_index = True)
df = temp.append(df2, ignore_index = True)
df.to_csv("visual_comp.csv")

In [3]:
df

,Unnamed: 0,username1,username2,link1,link2,comparison_type,ssim,features2d,stage,link1_change,link2_change,ssim_exp,group
0,0,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/BrandonAvilan...,http://www.ironhacks.com/preview/BrandonAvilan...,maps,10.1,100.0,1,BrandonAvilanR,BrandonAvilanR,89.9,0
1,9,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/DaniCastel/we...,http://www.ironhacks.com/preview/DaniCastel/we...,maps,6.5,39.9,1,DaniCastel,DaniCastel,93.5,0
2,50,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/Orloffyeah/we...,http://www.ironhacks.com/preview/Orloffyeah/we...,maps,37.1,67.2,1,Orloffyeah,Orloffyeah,62.9,0
3,67,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/alejosaur/web...,http://www.ironhacks.com/preview/alejosaur/web...,maps,68.1,87.8,1,alejosaur,alejosaur,31.9,0
4,84,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/anythinglord/...,http://www.ironhacks.com/preview/anythinglord/...,maps,28.2,32.8,1,anythinglord,anythinglord,71.8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,5848,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/pahigueraf/we...,http://www.ironhacks.com/preview/pahigueraf/we...,simple,96.6,100.0,4,pahigueraf,pahigueraf,3.4,2
705,5875,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/sarguellesr/w...,http://www.ironhacks.com/preview/sarguellesr/w...,simple,100.0,100.0,4,sarguellesr,sarguellesr,0.0,2
706,5902,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/uxjudges1/web...,http://www.ironhacks.com/preview/uxjudges1/web...,simple,100.0,100.0,4,uxjudges1,uxjudges1,0.0,2
707,5929,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/uxjudges/weba...,http://www.ironhacks.com/preview/uxjudges/weba...,simple,100.0,100.0,4,uxjudges,uxjudges,0.0,2
708,5956,www.ironhacks.com,www.ironhacks.com,http://www.ironhacks.com/preview/vvargasd/weba...,http://www.ironhacks.com/preview/vvargasd/weba...,simple,100.0,100.0,4,vvargasd,vvargasd,0.0,2

In [5]:
import pandas as pd

%store -r final_unal0_functions_complete
%store -r final_unal1_functions_complete
%store -r final_unal2_functions_complete

df = pd.read_csv("final_unal0_functions_complete.csv") 
df1 = pd.read_csv("final_unal1_functions_complete.csv") 
df2 = pd.read_csv("final_unal2_functions_complete.csv") 

df['group'] = 0
df1['group'] = 1
df2['group'] = 2

temp = df1.append(df)
final = df2.append(temp)

final['ssim_exp_latest'] = final['ssim_exp'].div(100).round(6)
final.loc[final['ssim_exp_latest'] == 0.0, 'ssim_exp_latest'] = 0.01
final.loc[final['ssim_exp_latest'] == 1.0, 'ssim_exp_latest'] = 0.99
final = final.rename(columns={'comparison_type': 'type', 'stage': 'phase', 'ssim_exp_latest': 'dist_search'})
df['comparison_type'] = df['comparison_type'].str.replace('complete', 'visual')
df['comparison_type'] = df['comparison_type'].str.replace('functions', 'code')
final.to_csv('final_functions.csv')

In [9]:
final['ssim_exp_new']

0      0.318182
1      0.272727
2      1.000000
3      0.484848
4      0.360000
         ...
166    0.000000
167    0.000000
168    0.506000
169    0.000000
170    0.409000
Name: ssim_exp_new, Length: 500, dtype: float64

In [13]:
final

,Unnamed: 0,link1_change,link2_change,ssim_exp,stage,comparison_type,group,ssim_exp_scale,ssim_exp_new
0,0,diefrodriguezcha,diefrodriguezcha,31.818182,1,functions,2,NaN,0.318182
1,1,adcorredorm,adcorredorm,27.272727,1,functions,2,NaN,0.272727
2,2,DaveValencia,DaveValencia,100.000000,1,functions,2,NaN,1.000000
3,3,pahigueraf,pahigueraf,48.484848,1,functions,2,NaN,0.484848
4,4,jannMorenoJ,jannMorenoJ,36.000000,1,functions,2,NaN,0.360000
...,...,...,...,...,...,...,...,...,...
166,166,dieguischa,dieguischa,0.000000,4,complete,0,0.010,0.000000
167,167,jaasuarezvi,jaasuarezvi,0.000000,4,complete,0,0.010,0.000000
168,168,jdsolanos,jdsolanos,50.600000,4,complete,0,0.506,0.506000
169,169,tres-xxx,tres-xxx,0.000000,4,complete,0,0.010,0.000000
170,170,trickyjuggler,trickyjuggler,40.900000,4,complete,0,0.409,0.409000